# Hent alle bruger
GET http://localhost:5024/admin/bruger

###

# Hent udvalgt bruger
GET http://localhost:5024/admin/bruger/5ee0b1dbc009874040ce495e

###

# Opret ny bruger
POST http://localhost:5024/admin/bruger
Content-Type: application/json

{
    "brugernavn": "heidiB",
    "email": "heidi@gmail.com",
    "password": "hemmelig"
}

###

# Ret en bruger

PATCH http://localhost:5024/admin/bruger/5ee0c2d640239a3984871960
Content-Type: application/json

{
    "password": "hej"
}

###

# Slet en bruger

DELETE http://localhost:5024/admin/bruger/5ee0b1dbc009874040ce495e
